// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scnvfxdzqxswipplukie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjbnZmeGR6cXhzd2lwcGx1a2llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTEwOTAsImV4cCI6MjA1Nzk4NzA5MH0.bqj_8VmMuAb1Uf-yXicp51k67lHyKhWedqdQc8Ds1Lk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);